/**
 * Pure, unit-testable helpers for the markdown-oxide `.moxide.toml` config.
 * Kept free of any Svelte/runes/Tauri imports so it can be tested with bun.
 */

export const DEFAULT_MOXIDE_TOML = `# markdown-oxide config (auto-generated by azprose)
# See https://oxide.md/Configuration
dailynote = "%Y-%m-%d"
heading_completions = true
callout_completions = true
title_headings = true
unresolved_diagnostics = true
semantic_tokens = true
tags_in_codeblocks = false
references_in_codeblocks = false
include_md_extension_md_link = true
include_md_extension_wikilink = true
hover = true
inlay_hints = true
block_transclusion = true
excluded_folders = [".azprose"]
`;

/**
 * Ensure `callout_completions = true` is present in a `.moxide.toml` content.
 *
 * markdown-oxide's LSP `CalloutCompleter` returns no items unless this setting
 * is enabled. Pure + idempotent (unit-tested): keeps the existing config,
 * inserts the line after `heading_completions` when possible, appends
 * otherwise.
 */
export function patchCalloutCompletions(toml: string): string {
  if (/^callout_completions\s*=/m.test(toml)) return toml;
  const withHeading = toml.replace(
    /^heading_completions = true\s*$/m,
    "heading_completions = true\ncallout_completions = true",
  );
  if (withHeading !== toml) return withHeading;
  return toml.endsWith("\n")
    ? toml + "callout_completions = true\n"
    : toml + "\ncallout_completions = true\n";
}
