export const STORAGE_KEYS = {
  themeMode: "mdview.theme",
  transparency: "mdview.transparency",
  sidebarOpen: "mdview.sidebar.open",
  sidebarWidth: "mdview.sidebar.width",
  lastFile: "mdview.lastFile",
  welcomed: "mdview.welcomed",
  lastSeenVersion: "mdview.lastSeenVersion",
  language: "mdview.language",
  titlebarVisible: "mdview.titlebar.visible",
  folders: "mdview.folders",
  favorites: "mdview.favorites",
  typography: "mdview.typography",
  proseMarkStyle: "mdview.prosemark.style",
  previewStyle: "mdview.preview.style",
  presentationStyle: "mdview.presentation.style",
  mathJaxPreamble: "mdview.mathjax.preamble",
  mathJaxPackages: "mdview.mathjax.packages",
  slideMode:  "mdview.slides.mode",
  defaultEditorMode: "mdview.default.editor.mode",
  callouts:   "mdview.callouts",
  latexSettings: "mdview.latex.settings",
  typstSettings: "mdview.typst.settings",
} as const;

export type StorageKey = (typeof STORAGE_KEYS)[keyof typeof STORAGE_KEYS];
