use std::fs;
use std::io::{BufRead, BufReader};
use std::path::{Path, PathBuf};
use std::process::{Command, Stdio};
use std::sync::{Arc, Mutex};
use std::thread;

use serde::Serialize;
use tauri::{AppHandle, Emitter};

mod synctex;
pub use synctex::*;

#[derive(Serialize)]
pub struct LatexBuildResult {
    pub pdf_path: Option<String>,
    pub diagnostics: Vec<LatexDiagnostic>,
    pub dependencies: Vec<String>,
}

#[derive(Serialize)]
pub struct LatexDiagnostic {
    pub severity: String,
    pub message: String,
    pub line: Option<u32>,
    pub col: Option<u32>,
    pub hints: Vec<String>,
    pub source: String,
}

#[derive(Clone, Serialize)]
struct LatexLogPayload {
    line: String,
}

fn engine_flag(engine: &str) -> &'static str {
    match engine {
        "xelatex" => "-xelatex",
        "lualatex" => "-lualatex",
        _ => "-pdf",
    }
}

fn parse_latexmkrc(dir: &Path) -> (Option<String>, Option<String>) {
    let mut current = Some(dir.to_path_buf());
    while let Some(ref cur) = current {
        let rc = cur.join("latexmkrc");
        if rc.exists() {
            return (parse_var(&rc, "$out_dir"), parse_var(&rc, "$aux_dir"));
        }
        current = cur.parent().map(|p| p.to_path_buf());
    }
    if let Some(home) = dirs::home_dir() {
        let rc = home.join(".latexmkrc");
        if rc.exists() {
            return (parse_var(&rc, "$out_dir"), parse_var(&rc, "$aux_dir"));
        }
    }
    (None, None)
}

fn parse_var(path: &Path, var: &str) -> Option<String> {
    let content = std::fs::read_to_string(path).ok()?;
    for line in content.lines() {
        let line = line.trim();
        let line = strip_perl_comment(line);
        if let Some(rest) = line.strip_prefix(var) {
            let rest = rest.trim_start();
            let rest = rest.strip_prefix('=')?;
            let v = rest.trim().trim_end_matches(';').trim();
            if v.is_empty() {
                continue;
            }
            if (v.starts_with('\'') && v.ends_with('\''))
                || (v.starts_with('"') && v.ends_with('"'))
            {
                return Some(v[1..v.len() - 1].to_string());
            }
            return Some(v.to_string());
        }
    }
    None
}

fn strip_perl_comment(line: &str) -> &str {
    let mut in_single = false;
    let mut in_double = false;
    for (i, ch) in line.char_indices() {
        match ch {
            '\'' if !in_double => in_single = !in_single,
            '"' if !in_single => in_double = !in_double,
            '#' if !in_single && !in_double => return &line[..i].trim_end(),
            _ => {}
        }
    }
    line
}

/// Parse the `.log` file generated by (pdf|xe|lua)latex for structured diagnostics.
/// This is more reliable than scraping latexmk's stdout because the log file has
/// the full error context with line numbers.
fn parse_log_file(path: &Path) -> Vec<LatexDiagnostic> {
    let content = match std::fs::read_to_string(path) {
        Ok(c) => c,
        Err(_) => return vec![],
    };

    let lines: Vec<&str> = content.lines().collect();
    let mut diags = Vec::new();
    let mut i = 0;

    while i < lines.len() {
        let line = lines[i];

        // Error: ! message
        if let Some(body) = line.strip_prefix("! ") {
            let msg = body.to_string();
            let mut line_num: Option<u32> = None;
            let mut context = String::new();

            // Look ahead for l.<line> pattern
            let mut j = i + 1;
            while j < lines.len() {
                let next = lines[j].trim();
                if let Some(rest) = next.strip_prefix("l.") {
                    // l.<line> [<context>]
                    let num_str = rest.split_whitespace().next().unwrap_or("");
                    line_num = num_str.parse::<u32>().ok();
                    context = rest.to_string();
                    break;
                }
                j += 1;
            }

            let full_msg = if context.is_empty() {
                msg
            } else {
                format!("{msg} — {context}")
            };
            diags.push(LatexDiagnostic {
                severity: "error".into(),
                message: full_msg,
                line: line_num,
                col: None,
                hints: Vec::new(),
                source: "latex".into(),
            });

            i = j.max(i + 1);
            continue;
        }

        // LaTeX Warning: … on input line <num>
        if let Some(body) = line.strip_prefix("LaTeX Warning: ") {
            let (l, msg) = extract_line_number(body);
            diags.push(LatexDiagnostic {
                severity: "warning".into(),
                message: msg,
                line: l,
                col: None,
                hints: Vec::new(),
                source: "latex".into(),
            });
            i += 1;
            continue;
        }

        // Package … Warning: …
        if line.contains(" Warning: ") {
            if line.starts_with("Package ") || line.starts_with("Class ") {
                let (l, msg) = extract_line_number(line);
                diags.push(LatexDiagnostic {
                    severity: "warning".into(),
                    message: msg,
                    line: l,
                    col: None,
                    hints: Vec::new(),
                    source: "latex".into(),
                });
                i += 1;
                continue;
            }
        }

        // Overfull / Underfull hbox/vbox — useful warnings
        if line.starts_with("Overfull") || line.starts_with("Underfull") {
            diags.push(LatexDiagnostic {
                severity: "warning".into(),
                message: line.to_string(),
                line: None,
                col: None,
                hints: Vec::new(),
                source: "latex".into(),
            });
            i += 1;
            continue;
        }

        i += 1;
    }

    diags
}

/// Extract `(line_number, cleaned_message)` from a warning line that may end with
/// `on input line <num>`.
fn extract_line_number(msg: &str) -> (Option<u32>, String) {
    if let Some(pos) = msg.rfind("on input line ") {
        let num_part = &msg[pos + "on input line ".len()..];
        let num_str: String = num_part.chars().take_while(|c| c.is_ascii_digit()).collect();
        if let Ok(n) = num_str.parse::<u32>() {
            let cleaned = msg[..pos].trim_end().to_string();
            return (Some(n), cleaned);
        }
    }
    (None, msg.to_string())
}

/// Parse latexmk stdout for status/error messages.
fn parse_latexmk_output(text: &str) -> Vec<LatexDiagnostic> {
    let mut diags = Vec::new();
    let lines: Vec<&str> = text.lines().collect();
    let mut i = 0;
    while i < lines.len() {
        let line = lines[i].trim();
        if line.starts_with("Latexmk:") {
            // Error conditions
            if line.contains("Could not find")
                || line.contains("missing")
                || line.contains("Errors")
            {
                diags.push(LatexDiagnostic {
                    severity: "error".into(),
                    message: line.to_string(),
                    line: None,
                    col: None,
                    hints: Vec::new(),
                    source: "latex".into(),
                });
            } else if line.contains("Warning") {
                diags.push(LatexDiagnostic {
                    severity: "warning".into(),
                    message: line.to_string(),
                    line: None,
                    col: None,
                    hints: Vec::new(),
                    source: "latex".into(),
                });
            }
        }
        // Catch-all: "! " errors — extract l.<line> if present on next lines
        if let Some(body) = line.strip_prefix("! ") {
            let mut line_num: Option<u32> = None;
            let mut context = String::new();
            // Look ahead for l.<line> pattern (same logic as parse_log_file)
            let mut j = i + 1;
            while j < lines.len() {
                let next = lines[j].trim();
                if let Some(rest) = next.strip_prefix("l.") {
                    let num_str = rest.split_whitespace().next().unwrap_or("");
                    line_num = num_str.parse::<u32>().ok();
                    context = rest.to_string();
                    break;
                }
                j += 1;
            }
            let full_msg = if !context.is_empty() {
                format!("{body} — {context}")
            } else {
                body.to_string()
            };
            diags.push(LatexDiagnostic {
                severity: "error".into(),
                message: full_msg,
                line: line_num,
                col: None,
                hints: Vec::new(),
                source: "latex".into(),
            });
        }
        i += 1;
    }
    diags
}

/// Resolve the output directory given a project dir and optional $out_dir value.
fn output_dir(dir: &Path, out_dir: &Option<String>) -> PathBuf {
    out_dir
        .as_ref()
        .map(|d| dir.join(d))
        .unwrap_or_else(|| dir.to_path_buf())
}

/// Parse the `.fls` file generated by latexmk -recorder.
/// Returns all INPUT files that sit inside the project directory
/// (excluding system packages from texmf-dist).
fn parse_fls_file(dir: &Path, out_dir_path: &Path, aux_dir_path: Option<&Path>, file_stem: &str) -> Vec<String> {
    let fls_path = out_dir_path.join(format!("{file_stem}.fls"));
    let mut content = std::fs::read_to_string(&fls_path);
    if content.is_err() {
        if let Some(aux) = aux_dir_path {
            if aux != out_dir_path {
                content = std::fs::read_to_string(aux.join(format!("{file_stem}.fls")));
            }
        }
    }
    let content = match content {
        Ok(c) => c,
        Err(_) => return vec![],
    };

    let project_root = dir.canonicalize().unwrap_or_else(|_| dir.to_path_buf());

    let mut deps: Vec<String> = Vec::new();
    let mut seen = std::collections::HashSet::new();

    for line in content.lines() {
        let line = line.trim();
        if let Some(path_str) = line.strip_prefix("INPUT ") {
            let path_str = path_str.trim();
            if path_str.is_empty() {
                continue;
            }
            let p = Path::new(path_str);
            let abs = if p.is_absolute() {
                p.to_path_buf()
            } else {
                dir.join(p)
            };

            // Only keep files inside the project directory tree
            if let Ok(canon) = abs.canonicalize() {
                if canon.starts_with(&project_root) && seen.insert(canon.clone()) {
                    if let Some(s) = canon.to_str() {
                        deps.push(s.to_string());
                    }
                }
            }
        }
    }

    deps
}

#[tauri::command]
pub async fn latex_build(
    path: String,
    engine: String,
    shell_escape: Option<bool>,
    max_runs: Option<u32>,
    out_dir: Option<String>,
    aux_dir: Option<String>,
    app: AppHandle,
) -> Result<LatexBuildResult, String> {
    if !check_latexmk() {
        app.emit(
            "latex://log",
            LatexLogPayload {
                line: "error: latexmk is not installed. Install TeX Live (texlive-core) or MiKTeX."
                    .into(),
            },
        )
        .ok();
        return Ok(LatexBuildResult {
            pdf_path: None,
            diagnostics: vec![LatexDiagnostic {
                severity: "error".into(),
                message: "latexmk is not installed. Install TeX Live (texlive-core on Arch) or MiKTeX to compile LaTeX."
                    .into(),
                line: None,
                col: None,
                hints: vec!["sudo pacman -S texlive-core".into()],
                source: "latex".into(),
            }],
            dependencies: vec![],
        });
    }

    let tex_path = Path::new(&path);
    let dir = tex_path
        .parent()
        .ok_or_else(|| "invalid file path".to_string())?;
    let file_stem = tex_path
        .file_stem()
        .and_then(|s| s.to_str())
        .ok_or_else(|| "invalid file name".to_string())?;
    let flag = engine_flag(&engine);

    let (rc_out_dir, rc_aux_dir) = parse_latexmkrc(dir);
    // Frontend settings override latexmkrc values
    let effective_out_dir = out_dir.or(rc_out_dir);
    let effective_aux_dir = aux_dir.or(rc_aux_dir);
    if let Some(ref d) = effective_out_dir {
        let _ = app.emit(
            "latex://log",
            LatexLogPayload {
                line: format!("info: output directory → {d}"),
            },
        );
    }
    if let Some(ref d) = effective_aux_dir {
        let _ = app.emit(
            "latex://log",
            LatexLogPayload {
                line: format!("info: aux directory → {d}"),
            },
        );
    }

    app.emit(
        "latex://log",
        LatexLogPayload {
            line: format!("info: running latexmk {flag} {file_stem}"),
        },
    )
    .ok();

    let mut cmd_args: Vec<String> = vec![flag.into(), "-synctex=1".into(), "-interaction=nonstopmode".into(), "-halt-on-error".into()];
    if shell_escape.unwrap_or(false) {
        // Warn: MiKTeX may restrict \write18
        if cfg!(target_os = "windows") || std::env::var("MSYSTEM").is_ok() {
            let _ = app.emit(
                "latex://log",
                LatexLogPayload {
                    line: "warning: --shell-escape on MiKTeX may be restricted. \\write18 requires elevated permissions.".into(),
                },
            );
        }
        cmd_args.push("--shell-escape".into());
    }
    if let Some(runs) = max_runs {
        if runs >= 1 && runs <= 20 {
            cmd_args.push(format!("-max_repeat={runs}"));
        }
    }
    if let Some(ref d) = effective_out_dir {
        cmd_args.push(format!("-outdir={d}"));
    }
    if let Some(ref d) = effective_aux_dir {
        cmd_args.push(format!("-auxdir={d}"));
    }
    cmd_args.push(file_stem.into());

    let mut child = Command::new("latexmk")
        .args(&cmd_args)
        .current_dir(dir)
        .stdout(Stdio::piped())
        .stderr(Stdio::piped())
        .spawn()
        .map_err(|e| format!("failed to run latexmk: {e}"))?;

    let stdout = child.stdout.take().unwrap();
    let stderr = child.stderr.take().unwrap();

    let full_stdout = Arc::new(Mutex::new(String::new()));
    let full_stderr = Arc::new(Mutex::new(String::new()));

    let app1 = app.clone();
    let out_buf = full_stdout.clone();
    let t1 = thread::spawn(move || {
        let reader = BufReader::new(stdout);
        for line in reader.lines() {
            if let Ok(line) = line {
                let _ = app1.emit("latex://log", LatexLogPayload { line: line.clone() });
                out_buf.lock().unwrap().push_str(&line);
                out_buf.lock().unwrap().push('\n');
            }
        }
    });

    let app2 = app.clone();
    let err_buf = full_stderr.clone();
    let t2 = thread::spawn(move || {
        let reader = BufReader::new(stderr);
        for line in reader.lines() {
            if let Ok(line) = line {
                let _ = app2.emit("latex://log", LatexLogPayload { line: line.clone() });
                err_buf.lock().unwrap().push_str(&line);
                err_buf.lock().unwrap().push('\n');
            }
        }
    });

    t1.join().map_err(|_| "stdout reader failed".to_string())?;
    t2.join().map_err(|_| "stderr reader failed".to_string())?;

    let _status = child.wait().map_err(|e| format!("failed to wait: {e}"))?;

    let stdout_text = full_stdout.lock().unwrap().clone();
    let stderr_text = full_stderr.lock().unwrap().clone();

    let mut diags = Vec::new();

    // 1. Parse the .log file for structured diagnostics (best source)
    let out_dir_path = output_dir(dir, &effective_out_dir);
    let log_path = out_dir_path.join(format!("{file_stem}.log"));
    if log_path.exists() {
        diags.extend(parse_log_file(&log_path));
    }

    // 2. Parse latexmk stdout for status messages (fallback / supplement)
    diags.extend(parse_latexmk_output(&stdout_text));
    diags.extend(parse_latexmk_output(&stderr_text));

    // 3. Deduplicate: keep first occurrence of each unique (severity, message) pair
    {
        let mut seen = std::collections::HashSet::new();
        diags.retain(|d| seen.insert((d.severity.clone(), d.message.clone())));
    }

    // 4. Parse .fls for dependency tracking (try out_dir first, then aux_dir)
    let aux_dir_path = effective_aux_dir.as_ref().map(|d| dir.join(d));
    let dependencies = parse_fls_file(dir, &out_dir_path, aux_dir_path.as_deref(), file_stem);
    let dep_count = dependencies.len();
    let _ = app.emit(
        "latex://log",
        LatexLogPayload {
            line: format!("info: tracked {dep_count} file dependencies from .fls"),
        },
    );

    let pdf_path = out_dir_path.join(format!("{file_stem}.pdf"));

    // Emit build completion on BOTH latex://log (visible in Log tab) and latex://build-complete
    let completion_msg = if pdf_path.exists() {
        format!("info: build finished – {}", pdf_path.display())
    } else {
        "error: build failed – no PDF output".into()
    };
    let _ = app.emit("latex://log", LatexLogPayload { line: completion_msg.clone() });
    let _ = app.emit("latex://build-complete", LatexLogPayload { line: completion_msg });

    if pdf_path.exists() {
        Ok(LatexBuildResult {
            pdf_path: Some(pdf_path.to_string_lossy().to_string()),
            diagnostics: diags,
            dependencies,
        })
    } else {
        if diags.is_empty() {
            diags.push(LatexDiagnostic {
                severity: "error".into(),
                message: "latexmk failed with no PDF output and no parseable diagnostics."
                    .into(),
                line: None,
                col: None,
                hints: vec![
                    "check that latexmk / LaTeX distribution is correctly installed".into(),
                ],
                source: "latex".into(),
            });
        }
        Ok(LatexBuildResult {
            pdf_path: None,
            diagnostics: diags,
            dependencies,
        })
    }
}

#[tauri::command]
pub fn check_latexmk() -> bool {
    Command::new("latexmk")
        .arg("-v")
        .output()
        .map(|o| o.status.success())
        .unwrap_or(false)
}

// ── Root file detection (replicates texlab algorithm) ────────────────

#[derive(Serialize)]
pub struct LatexRootResult {
    /// The detected root .tex file path, or `None` if unsure.
    pub root_file: Option<String>,
    /// Human-readable info about how the root was found.
    pub method: String,
}

/// Find the root directory by traversing upward looking for marker files.
/// Returns the directory containing the marker, or the file's own directory.
fn find_root_dir(start: &Path) -> (std::path::PathBuf, String) {
    // Phase A — traverse up looking for project markers
    let mut cur = Some(start.to_path_buf());
    while let Some(ref dir) = cur {
        // .texlabroot / texlabroot
        if dir.join(".texlabroot").exists() {
            return (dir.clone(), ".texlabroot".into());
        }
        if dir.join("texlabroot").exists() {
            return (dir.clone(), "texlabroot".into());
        }
        // Tectonic.toml
        if dir.join("Tectonic.toml").exists() {
            return (dir.clone(), "Tectonic.toml".into());
        }
        // .latexmkrc / latexmkrc
        if dir.join(".latexmkrc").exists() {
            return (dir.clone(), ".latexmkrc".into());
        }
        if dir.join("latexmkrc").exists() {
            return (dir.clone(), "latexmkrc".into());
        }
        cur = dir.parent().map(|p| p.to_path_buf());
    }
    // Fallback: use the starting directory
    (start.to_path_buf(), "default (file directory)".into())
}

/// Check if a .tex file contains `\documentclass` and is not a subfile.
/// Returns true if the file has `\documentclass` but NOT
/// `\documentclass{subfiles}` or `\documentclass{cpgesubdoc}`.
fn has_documentclass(path: &Path) -> bool {
    let content = match std::fs::read_to_string(path) {
        Ok(c) => c,
        Err(_) => return false,
    };
    // Quick check: does it contain \documentclass at all?
    if !content.contains("\\documentclass") {
        return false;
    }
    // Check for excluded classes: \documentclass{subfiles} or \documentclass{cpgesubdoc}
    let lowered = content.to_lowercase();
    for excluded in &["subfiles", "cpgesubdoc"] {
        let pattern = format!("\\documentclass{{{excluded}}}");
        if lowered.contains(&pattern.to_lowercase()) {
            return false;
        }
    }
    true
}

/// Detect the LaTeX root file for a given .tex file.
///
/// Algorithm (replicates texlab's `deps/root.rs`):
/// 1. Find root directory via marker files (.texlabroot, Tectonic.toml, .latexmkrc)
/// 2. Walk from file upward to root_dir, scanning each directory for .tex files with
///    `\documentclass` (excluding subfiles/cpgesubdoc). Pick the highest one.
/// 3. Fallback: return the file itself
#[tauri::command]
pub fn latex_find_root(path: String) -> LatexRootResult {
    let tex_path = Path::new(&path);
    let file_dir = match tex_path.parent() {
        Some(d) => d,
        None => {
            return LatexRootResult {
                root_file: None,
                method: "invalid path".into(),
            }
        }
    };

    // Phase A: find root directory via markers
    let (root_dir, dir_method) = find_root_dir(file_dir);

    // Phase B: walk from file's directory upward to root_dir, at each level scan for
    // .tex files with \documentclass. The highest one (closest to root) is the root.
    // If no markers were found (root_dir == file_dir), walk all the way up to "/".
    let effective_root = if root_dir == file_dir {
        PathBuf::from("/")
    } else {
        root_dir.clone()
    };
    let mut root_candidates: Vec<std::path::PathBuf> = Vec::new();
    let mut cur_dir = std::path::PathBuf::from(file_dir);
    loop {
        // Scan .tex files in this directory for \documentclass
        if let Ok(entries) = std::fs::read_dir(&cur_dir) {
            for entry in entries.flatten() {
                let p = entry.path();
                if p.extension().and_then(|e| e.to_str()) == Some("tex") && has_documentclass(&p)
                {
                    root_candidates.push(p);
                }
            }
        }
        // Stop once we've reached the effective root
        if cur_dir == effective_root {
            break;
        }
        match cur_dir.parent() {
            Some(parent) => cur_dir = parent.to_path_buf(),
            None => break,
        }
    }

    // root_candidates is ordered deepest-first; the first entry with \documentclass
    // at the deepest level is the original file (if it qualifies). The last entry
    // (highest in the tree) is the best root candidate.
    //
    // Prefer the current file if it has \documentclass; otherwise use the highest ancestor.
    if has_documentclass(tex_path) {
        LatexRootResult {
            root_file: Some(path.clone()),
            method: format!("current file has \\documentclass ({dir_method})"),
        }
    } else if let Some(best) = root_candidates.last() {
        LatexRootResult {
            root_file: Some(best.to_string_lossy().to_string()),
            method: format!(
                "highest \\documentclass in {dir_method} scan ({} candidates)",
                root_candidates.len()
            ),
        }
    } else {
        LatexRootResult {
            root_file: Some(path.clone()),
            method: "fallback: no \\documentclass found, using current file".into(),
        }
    }
}

/// Initialize .azprose/texmf/ with TDS structure and run mktexlsr.
#[tauri::command]
pub fn latex_init_texmf(project_root: String) -> Result<String, String> {
    let texmf = Path::new(&project_root).join(".azprose").join("texmf");

    // Create TDS directories
    let dirs = [
        "tex/latex",
        "bibtex/bst",
        "bibtex/bib",
        "fonts",
    ];
    for d in &dirs {
        let full = texmf.join(d);
        fs::create_dir_all(&full).map_err(|e| format!("create {d}: {e}"))?;
    }

    Ok("texmf directory created".into())
}

/// Run mktexlsr/texhash on .azprose/texmf/ to rebuild the ls-R database.
#[tauri::command]
pub fn latex_rehash_texmf(project_root: String) -> Result<String, String> {
    let texmf = Path::new(&project_root).join(".azprose").join("texmf");
    if !texmf.exists() {
        return Err("texmf directory does not exist".into());
    }

    // Try mktexlsr first, then texhash
    for cmd in &["mktexlsr", "texhash"] {
        let output = std::process::Command::new(cmd)
            .arg(texmf.to_string_lossy().to_string())
            .output();
        match output {
            Ok(o) if o.status.success() => {
                let msg = String::from_utf8_lossy(&o.stdout);
                return Ok(format!("{cmd} — {msg}"));
            }
            Ok(o) => {
                let err = String::from_utf8_lossy(&o.stderr);
                if !err.contains("not found") && !err.contains("No such file") {
                    return Ok(format!("{cmd} warning: {err}"));
                }
            }
            Err(_) => continue,
        }
    }
    Ok("ls-R not generated — mktexlsr/texhash not found (file lookup still works via TEXMFHOME)".into())
}
