use std::io::{BufRead, BufReader};
use std::path::Path;
use std::process::{Command, Stdio};
use std::sync::{Arc, Mutex};
use std::thread;

use serde::Serialize;
use tauri::{AppHandle, Emitter};

#[derive(Serialize)]
pub struct LatexBuildResult {
    pub pdf_path: Option<String>,
    pub diagnostics: Vec<LatexDiagnostic>,
}

#[derive(Serialize)]
pub struct LatexDiagnostic {
    pub severity: String,
    pub message: String,
    pub line: Option<u32>,
    pub col: Option<u32>,
    pub hints: Vec<String>,
    pub source: String,
}

#[derive(Clone, Serialize)]
struct LatexLogPayload {
    line: String,
}

fn engine_flag(engine: &str) -> &'static str {
    match engine {
        "xelatex" => "-xelatex",
        "lualatex" => "-lualatex",
        _ => "-pdf",
    }
}

fn parse_latexmkrc(dir: &Path) -> Option<String> {
    let mut current = Some(dir.to_path_buf());
    while let Some(ref cur) = current {
        let rc = cur.join("latexmkrc");
        if rc.exists() {
            return parse_out_dir(&rc);
        }
        current = cur.parent().map(|p| p.to_path_buf());
    }
    if let Some(home) = dirs::home_dir() {
        let rc = home.join(".latexmkrc");
        if rc.exists() {
            return parse_out_dir(&rc);
        }
    }
    None
}

fn parse_out_dir(path: &Path) -> Option<String> {
    let content = std::fs::read_to_string(path).ok()?;
    for line in content.lines() {
        let line = line.trim();
        let line = strip_perl_comment(line);
        if let Some(rest) = line.strip_prefix("$out_dir") {
            let rest = rest.trim_start();
            let rest = rest.strip_prefix('=')?;
            let v = rest.trim().trim_end_matches(';').trim();
            if v.is_empty() {
                continue;
            }
            if (v.starts_with('\'') && v.ends_with('\''))
                || (v.starts_with('"') && v.ends_with('"'))
            {
                return Some(v[1..v.len() - 1].to_string());
            }
            return Some(v.to_string());
        }
    }
    None
}

fn strip_perl_comment(line: &str) -> &str {
    let mut in_single = false;
    let mut in_double = false;
    for (i, ch) in line.char_indices() {
        match ch {
            '\'' if !in_double => in_single = !in_single,
            '"' if !in_single => in_double = !in_double,
            '#' if !in_single && !in_double => return &line[..i].trim_end(),
            _ => {}
        }
    }
    line
}

/// Parse the `.log` file generated by (pdf|xe|lua)latex for structured diagnostics.
/// This is more reliable than scraping latexmk's stdout because the log file has
/// the full error context with line numbers.
fn parse_log_file(path: &Path) -> Vec<LatexDiagnostic> {
    let content = match std::fs::read_to_string(path) {
        Ok(c) => c,
        Err(_) => return vec![],
    };

    let lines: Vec<&str> = content.lines().collect();
    let mut diags = Vec::new();
    let mut i = 0;

    while i < lines.len() {
        let line = lines[i];

        // Error: ! message
        if let Some(body) = line.strip_prefix("! ") {
            let msg = body.to_string();
            let mut line_num: Option<u32> = None;
            let mut context = String::new();

            // Look ahead for l.<line> pattern
            let mut j = i + 1;
            while j < lines.len() {
                let next = lines[j].trim();
                if let Some(rest) = next.strip_prefix("l.") {
                    // l.<line> [<context>]
                    let num_str = rest.split_whitespace().next().unwrap_or("");
                    line_num = num_str.parse::<u32>().ok();
                    context = rest.to_string();
                    break;
                }
                j += 1;
            }

            let full_msg = if context.is_empty() {
                msg
            } else {
                format!("{msg} — {context}")
            };
            diags.push(LatexDiagnostic {
                severity: "error".into(),
                message: full_msg,
                line: line_num,
                col: None,
                hints: Vec::new(),
                source: "latex".into(),
            });

            i = j.max(i + 1);
            continue;
        }

        // LaTeX Warning: … on input line <num>
        if let Some(body) = line.strip_prefix("LaTeX Warning: ") {
            let (l, msg) = extract_line_number(body);
            diags.push(LatexDiagnostic {
                severity: "warning".into(),
                message: msg,
                line: l,
                col: None,
                hints: Vec::new(),
                source: "latex".into(),
            });
            i += 1;
            continue;
        }

        // Package … Warning: …
        if line.contains(" Warning: ") {
            if line.starts_with("Package ") || line.starts_with("Class ") {
                let (l, msg) = extract_line_number(line);
                diags.push(LatexDiagnostic {
                    severity: "warning".into(),
                    message: msg,
                    line: l,
                    col: None,
                    hints: Vec::new(),
                    source: "latex".into(),
                });
                i += 1;
                continue;
            }
        }

        // Overfull / Underfull hbox/vbox — useful warnings
        if line.starts_with("Overfull") || line.starts_with("Underfull") {
            diags.push(LatexDiagnostic {
                severity: "warning".into(),
                message: line.to_string(),
                line: None,
                col: None,
                hints: Vec::new(),
                source: "latex".into(),
            });
            i += 1;
            continue;
        }

        i += 1;
    }

    diags
}

/// Extract `(line_number, cleaned_message)` from a warning line that may end with
/// `on input line <num>`.
fn extract_line_number(msg: &str) -> (Option<u32>, String) {
    if let Some(pos) = msg.rfind("on input line ") {
        let num_part = &msg[pos + "on input line ".len()..];
        let num_str: String = num_part.chars().take_while(|c| c.is_ascii_digit()).collect();
        if let Ok(n) = num_str.parse::<u32>() {
            let cleaned = msg[..pos].trim_end().to_string();
            return (Some(n), cleaned);
        }
    }
    (None, msg.to_string())
}

/// Parse latexmk stdout for status/error messages.
fn parse_latexmk_output(text: &str) -> Vec<LatexDiagnostic> {
    let mut diags = Vec::new();
    for line in text.lines() {
        let line = line.trim();
        if line.starts_with("Latexmk:") {
            // Error conditions
            if line.contains("Could not find") || line.contains("missing") || line.contains("Errors") {
                diags.push(LatexDiagnostic {
                    severity: "error".into(),
                    message: line.to_string(),
                    line: None,
                    col: None,
                    hints: Vec::new(),
                    source: "latex".into(),
                });
            } else if line.contains("Warning") {
                diags.push(LatexDiagnostic {
                    severity: "warning".into(),
                    message: line.to_string(),
                    line: None,
                    col: None,
                    hints: Vec::new(),
                    source: "latex".into(),
                });
            }
        }
        // Catch-all: "! " errors in stdout that weren't in the log file
        if let Some(body) = line.strip_prefix("! ") {
            diags.push(LatexDiagnostic {
                severity: "error".into(),
                message: body.to_string(),
                line: None,
                col: None,
                hints: Vec::new(),
                source: "latex".into(),
            });
        }
    }
    diags
}

/// Resolve the output directory given a project dir and optional $out_dir value.
fn output_dir(dir: &Path, out_dir: &Option<String>) -> std::path::PathBuf {
    out_dir
        .as_ref()
        .map(|d| dir.join(d))
        .unwrap_or_else(|| dir.to_path_buf())
}

#[tauri::command]
pub async fn latex_build(
    path: String,
    engine: String,
    app: AppHandle,
) -> Result<LatexBuildResult, String> {
    if !check_latexmk() {
        app.emit(
            "latex://log",
            LatexLogPayload {
                line: "error: latexmk is not installed. Install TeX Live (texlive-core) or MiKTeX."
                    .into(),
            },
        )
        .ok();
        return Ok(LatexBuildResult {
            pdf_path: None,
            diagnostics: vec![LatexDiagnostic {
                severity: "error".into(),
                message: "latexmk is not installed. Install TeX Live (texlive-core on Arch) or MiKTeX to compile LaTeX."
                    .into(),
                line: None,
                col: None,
                hints: vec!["sudo pacman -S texlive-core".into()],
                source: "latex".into(),
            }],
        });
    }

    let tex_path = Path::new(&path);
    let dir = tex_path
        .parent()
        .ok_or_else(|| "invalid file path".to_string())?;
    let file_stem = tex_path
        .file_stem()
        .and_then(|s| s.to_str())
        .ok_or_else(|| "invalid file name".to_string())?;
    let flag = engine_flag(&engine);

    let out_dir = parse_latexmkrc(dir);
    if let Some(ref d) = out_dir {
        let _ = app.emit(
            "latex://log",
            LatexLogPayload {
                line: format!("info: output directory from latexmkrc → {d}"),
            },
        );
    }

    app.emit(
        "latex://log",
        LatexLogPayload {
            line: format!("info: running latexmk {flag} {file_stem}"),
        },
    )
    .ok();

    let mut child = Command::new("latexmk")
        .args([flag, "-interaction=nonstopmode", "-halt-on-error", file_stem])
        .current_dir(dir)
        .stdout(Stdio::piped())
        .stderr(Stdio::piped())
        .spawn()
        .map_err(|e| format!("failed to run latexmk: {e}"))?;

    let stdout = child.stdout.take().unwrap();
    let stderr = child.stderr.take().unwrap();

    let full_stdout = Arc::new(Mutex::new(String::new()));
    let full_stderr = Arc::new(Mutex::new(String::new()));

    let app1 = app.clone();
    let out_buf = full_stdout.clone();
    let t1 = thread::spawn(move || {
        let reader = BufReader::new(stdout);
        for line in reader.lines() {
            if let Ok(line) = line {
                let _ = app1.emit("latex://log", LatexLogPayload { line: line.clone() });
                out_buf.lock().unwrap().push_str(&line);
                out_buf.lock().unwrap().push('\n');
            }
        }
    });

    let app2 = app.clone();
    let err_buf = full_stderr.clone();
    let t2 = thread::spawn(move || {
        let reader = BufReader::new(stderr);
        for line in reader.lines() {
            if let Ok(line) = line {
                let _ = app2.emit("latex://log", LatexLogPayload { line: line.clone() });
                err_buf.lock().unwrap().push_str(&line);
                err_buf.lock().unwrap().push('\n');
            }
        }
    });

    t1.join().map_err(|_| "stdout reader failed".to_string())?;
    t2.join().map_err(|_| "stderr reader failed".to_string())?;

    let _status = child.wait().map_err(|e| format!("failed to wait: {e}"))?;

    let stdout_text = full_stdout.lock().unwrap().clone();
    let stderr_text = full_stderr.lock().unwrap().clone();

    let mut diags = Vec::new();

    // 1. Parse the .log file for structured diagnostics (best source)
    let out_dir_path = output_dir(dir, &out_dir);
    let log_path = out_dir_path.join(format!("{file_stem}.log"));
    if log_path.exists() {
        diags.extend(parse_log_file(&log_path));
    }

    // 2. Parse latexmk stdout for status messages (fallback / supplement)
    diags.extend(parse_latexmk_output(&stdout_text));
    diags.extend(parse_latexmk_output(&stderr_text));

    // 3. Deduplicate: keep first occurrence of each unique (severity, message) pair
    {
        let mut seen = std::collections::HashSet::new();
        diags.retain(|d| seen.insert((d.severity.clone(), d.message.clone())));
    }

    let pdf_path = out_dir_path.join(format!("{file_stem}.pdf"));

    let _ = app.emit(
        "latex://build-complete",
        LatexLogPayload {
            line: if pdf_path.exists() {
                format!("info: build finished – {}", pdf_path.display())
            } else {
                "error: build finished – no PDF output".into()
            },
        },
    );

    if pdf_path.exists() {
        Ok(LatexBuildResult {
            pdf_path: Some(pdf_path.to_string_lossy().to_string()),
            diagnostics: diags,
        })
    } else {
        if diags.is_empty() {
            diags.push(LatexDiagnostic {
                severity: "error".into(),
                message: "latexmk failed with no PDF output and no parseable diagnostics."
                    .into(),
                line: None,
                col: None,
                hints: vec![
                    "check that latexmk / LaTeX distribution is correctly installed".into(),
                ],
                source: "latex".into(),
            });
        }
        Ok(LatexBuildResult {
            pdf_path: None,
            diagnostics: diags,
        })
    }
}

#[tauri::command]
pub fn check_latexmk() -> bool {
    Command::new("latexmk")
        .arg("-v")
        .output()
        .map(|o| o.status.success())
        .unwrap_or(false)
}
