import { describe, expect, test } from "bun:test";
import {
  OBSIDIAN_CALLOUT_TYPES,
  parseCalloutContext,
  buildCalloutCompletions,
} from "@/lib/callout-completion";
import { patchCalloutCompletions } from "@/lib/moxide-config";

describe("parseCalloutContext", () => {
  test("déclenche sur un callout ouvert dans une citation simple", () => {
    expect(parseCalloutContext("> [!")).toEqual({
      nested: 1,
      prefix: "> ",
      typed: "",
      fromDelta: 2,
    });
  });

  test("capture le nom partiellement tapé", () => {
    expect(parseCalloutContext("> [!theo")).toEqual({
      nested: 1,
      prefix: "> ",
      typed: "theo",
      fromDelta: 6,
    });
  });

  test("supporte les citations imbriquées", () => {
    expect(parseCalloutContext("> > [!exercise")).toEqual({
      nested: 2,
      prefix: "> > ",
      typed: "exercise",
      fromDelta: 10,
    });
  });

  test("supporte les marqueurs > sans espace", () => {
    expect(parseCalloutContext(">>[!def")).toEqual({
      nested: 2,
      prefix: ">>",
      typed: "def",
      fromDelta: 5,
    });
  });

  test("ne déclenche pas sur un callout déjà fermé", () => {
    expect(parseCalloutContext("> [!note] titre")).toBeNull();
  });

  test("ne déclenche pas sans préfixe de citation", () => {
    expect(parseCalloutContext("du texte [!")).toBeNull();
  });

  test("ne déclenche pas dans une citation sans callout", () => {
    expect(parseCalloutContext("> du texte")).toBeNull();
  });

  test("ne déclenche pas sur une citation qui n'est pas en tête", () => {
    expect(parseCalloutContext("texte > [!note")).toBeNull();
  });

  test("ne déclenche pas sur une ligne vide", () => {
    expect(parseCalloutContext("")).toBeNull();
  });
});

describe("buildCalloutCompletions", () => {
  const callouts = [
    { name: "theorem", label: "Théorème" },
    { name: "definition", label: "Définition" },
    { name: "remark", label: "Remarque" },
    { name: "example", label: "Exemple" },
    { name: "mesnotes", label: "Mes notes" },
  ];

  test("propose les callouts custom", () => {
    const labels = buildCalloutCompletions(callouts).map((c) => c.label);
    expect(labels).toContain("theorem");
    expect(labels).toContain("definition");
    expect(labels).toContain("mesnotes");
  });

  test("exclut les types déjà couverts par le LSP (aucun doublon)", () => {
    const names = buildCalloutCompletions(callouts).map((c) => c.label);
    // "example" est un type Obsidian officiel (listé par markdown-oxide)
    expect(names).not.toContain("example");
    expect(OBSIDIAN_CALLOUT_TYPES.has("example")).toBe(true);
  });

  test("applique la forme fermée avec un espace", () => {
    const item = buildCalloutCompletions(callouts)[0];
    expect(item.apply).toBe(`[!${item.label}] `);
  });

  test("retourne une liste vide si tous les callouts sont couverts par le LSP", () => {
    const allCovered = [...OBSIDIAN_CALLOUT_TYPES].map((name) => ({ name, label: name }));
    expect(buildCalloutCompletions(allCovered)).toEqual([]);
  });
});

describe("patchCalloutCompletions", () => {
  test("insère la clé après heading_completions", () => {
    const input = `dailynote = "%Y-%m-%d"
heading_completions = true
title_headings = true
`;
    const out = patchCalloutCompletions(input);
    expect(out).toBe(`dailynote = "%Y-%m-%d"
heading_completions = true
callout_completions = true
title_headings = true
`);
  });

  test("est idempotent : ne réinsère pas si la clé existe déjà", () => {
    const input = `heading_completions = true
callout_completions = true
title_headings = true
`;
    expect(patchCalloutCompletions(input)).toBe(input);
  });

  test("ajoute la clé en fin de fichier sans heading_completions", () => {
    const input = `dailynote = "%Y-%m-%d"
title_headings = true
`;
    const out = patchCalloutCompletions(input);
    expect(out.endsWith("\ncallout_completions = true\n")).toBe(true);
    expect(out.match(/callout_completions = true/g)).toHaveLength(1);
  });

  test("ajoute la clé avec un retour à la ligne manquant", () => {
    const input = "dailynote = \"%Y-%m-%d\"";
    const out = patchCalloutCompletions(input);
    expect(out.endsWith("\ncallout_completions = true\n")).toBe(true);
  });

  test("préserve le template par défaut (déjà complet)", () => {
    const tpl = `# markdown-oxide config (auto-generated by azprose)
dailynote = "%Y-%m-%d"
heading_completions = true
callout_completions = true
title_headings = true
`;
    expect(patchCalloutCompletions(tpl)).toBe(tpl);
  });
});
