// Offline theme build (run manually, NOT part of the app build).
//
//   node scripts/build-themes.mjs
//
// Single source of truth = src/styles/themes.json (BUILTIN themes, hand-editable).
// Structural CSS (constants, no-theme fallback, transparency) = src/styles/tokens.base.css
// with a `/* @THEMES@ */` placeholder. This script renders the per-theme blocks from
// themes.json into that placeholder and writes the generated src/styles/tokens.css.
//
// First run is a BOOTSTRAP: if themes.json / tokens.base.css don't exist yet, they are
// extracted from the current tokens.css so the regenerated file is byte-identical.

import { readFileSync, writeFileSync, existsSync } from "node:fs";
import { fileURLToPath } from "node:url";
import { dirname, resolve } from "node:path";

const root = resolve(dirname(fileURLToPath(import.meta.url)), "..");
const TOKENS = resolve(root, "src/styles/tokens.css");
const BASE = resolve(root, "src/styles/tokens.base.css");
const JSON_SRC = resolve(root, "src/styles/themes.json");

const FIRST_THEME_MARKER = /\/\*[^*]*\*\/\s*\n:root\[data-theme=/; // first per-theme block
const FALLBACK_MARKER = "/* fallback when no data-theme"; // start of the tail

// Parse the per-theme blocks of a CSS string into structured theme entries.
function parseThemes(css) {
  const blockRe =
    /(?:\/\*\s*([^*]*?)\s*\*\/\s*)?((?:\s*:root\[data-theme="[^"]+"\]\s*,?)+)\s*\{([\s\S]*?)\}/g;
  const themes = [];
  let m;
  while ((m = blockRe.exec(css)) !== null) {
    const comment = (m[1] || "").trim();
    const names = [...m[2].matchAll(/data-theme="([^"]+)"/g)].map((x) => x[1]);
    const body = m[3];
    const vars = {};
    let colorScheme = null;
    for (const line of body.split("\n")) {
      // value = everything up to the first ';' (ignores trailing /* palette */ comments)
      const v = line.match(/^\s*(--[a-z0-9-]+)\s*:\s*([^;]+);/i);
      if (v) { vars[v[1]] = v[2].trim(); continue; }
      const cs = line.match(/^\s*color-scheme\s*:\s*([^;]+);/i);
      if (cs) colorScheme = cs[1].trim();
    }
    themes.push({ names, comment, colorScheme, vars });
  }
  return themes;
}

// Render structured themes back to CSS per-theme blocks (stable key order).
const VAR_ORDER = [
  "--bg", "--bg-rgb", "--fg", "--muted", "--border", "--accent",
  "--surface", "--surface-hover", "--shadow-soft", "--color-error",
  "--backdrop", "--shadow-color",
  "--syntax-keyword", "--syntax-string", "--syntax-number", "--syntax-type",
  "--syntax-function", "--syntax-operator", "--syntax-comment", "--syntax-constant",
];

function renderThemes(themes) {
  const blocks = themes.map((t) => {
    const selector = t.names.map((n) => `:root[data-theme="${n}"]`).join(",\n");
    const keys = [
      ...VAR_ORDER.filter((k) => k in t.vars),
      ...Object.keys(t.vars).filter((k) => !VAR_ORDER.includes(k)),
    ];
    const decls = keys.map((k) => `  ${k}: ${t.vars[k]};`).join("\n");
    const scheme = t.colorScheme ? `\n  color-scheme: ${t.colorScheme};` : "";
    const comment = t.comment ? `/* ${t.comment} */\n` : "";
    return `${comment}${selector} {\n${decls}${scheme}\n}`;
  });
  return blocks.join("\n\n");
}

function bootstrap() {
  const css = readFileSync(TOKENS, "utf8");
  const startMatch = css.match(FIRST_THEME_MARKER);
  if (!startMatch) throw new Error("Could not locate first theme block in tokens.css");
  const start = startMatch.index;
  const foot = css.indexOf(FALLBACK_MARKER);
  if (foot < 0) throw new Error("Could not locate fallback marker in tokens.css");

  const head = css.slice(0, start).replace(/\s+$/, "") + "\n\n";
  const tail = "\n\n" + css.slice(foot);
  const themeRegion = css.slice(start, foot);

  const themes = parseThemes(themeRegion);

  writeFileSync(JSON_SRC, JSON.stringify({ themes }, null, 2) + "\n", "utf8");
  writeFileSync(BASE, head + "/* @THEMES@ */" + tail, "utf8");
  console.log(`bootstrap: ${themes.length} themes → themes.json + tokens.base.css`);
}

function build() {
  if (!existsSync(JSON_SRC) || !existsSync(BASE)) bootstrap();
  const { themes } = JSON.parse(readFileSync(JSON_SRC, "utf8"));
  const base = readFileSync(BASE, "utf8");
  const out =
    "/* GENERATED by scripts/build-themes.mjs — edit src/styles/themes.json, not this file. */\n" +
    base.replace("/* @THEMES@ */", renderThemes(themes));
  writeFileSync(TOKENS, out, "utf8");
  console.log(`build: tokens.css ← tokens.base.css + themes.json (${themes.length} themes)`);
  return themes;
}

// ── Fragment de boot (vague 2, phase 2.5) ────────────────────────────────
// index.html ET nav.html peignent #boot AVANT tout JS de l'app (script
// inline, lu directement dans localStorage) — ils ont chacun leur PROPRE
// copie des tables BG (fond par thème) / LIGHT (thèmes clairs), désormais
// régénérées ici plutôt que recopiées à la main : deux points d'entrée à
// tenir cohérents (phase 2.2) est exactement ce qui rend cette duplication
// dangereuse à laisser manuelle (un thème ajouté sans mettre à jour les DEUX
// fichiers → flash silencieux dans l'un des deux au démarrage).
const HTML_TARGETS = [resolve(root, "index.html"), resolve(root, "nav.html")];
const FRAGMENT_START = /\/\* GÉNÉRÉ par scripts\/build-themes\.mjs[\s\S]*?\*\/\n(\s*)var BG = \{[\s\S]*?\};\n\s*var LIGHT = \{[\s\S]*?\};\n\s*\/\* \/GÉNÉRÉ \*\//;

function isBareIdentifier(name) {
  return /^[a-zA-Z_$][a-zA-Z0-9_$]*$/.test(name);
}

function quoteKey(name) {
  return isBareIdentifier(name) ? name : `'${name}'`;
}

function renderBootFragment(themes, indent) {
  // Nom canonique = le PREMIER de `names` (les alias comme "light"/"dark" ne
  // sont jamais entrés dans ces tables — convention déjà en place à la main).
  const entries = themes.map((t) => ({ key: t.names[0], bg: t.vars["--bg"], light: t.colorScheme === "light" }));
  const width = Math.max(...entries.map((e) => quoteKey(e.key).length + 1)); // +1 pour le ":"
  const bgLines = entries
    .map((e) => `${indent}  ${(quoteKey(e.key) + ":").padEnd(width)} '${e.bg}',`)
    .join("\n");
  const lightKeys = entries.filter((e) => e.light).map((e) => `${quoteKey(e.key)}: 1`).join(", ");
  return (
    `/* GÉNÉRÉ par scripts/build-themes.mjs depuis themes.json — NE PAS\n` +
    `${indent}   éditer les tables BG/LIGHT ci-dessous à la main (vague 2, phase\n` +
    `${indent}   2.5). Éditer src/styles/themes.json, puis \`bun run themes\`. */\n` +
    `${indent}var BG = {\n${bgLines}\n${indent}};\n` +
    `${indent}var LIGHT = {\n${indent}  ${lightKeys},\n${indent}};\n` +
    `${indent}/* /GÉNÉRÉ */`
  );
}

function buildBootFragments(themes) {
  for (const path of HTML_TARGETS) {
    const html = readFileSync(path, "utf8");
    const m = html.match(FRAGMENT_START);
    if (!m) throw new Error(`boot: marqueur GÉNÉRÉ introuvable dans ${path} (bloc BG/LIGHT renommé ou supprimé ?)`);
    const indent = m[1];
    const fragment = renderBootFragment(themes, indent);
    const out = html.slice(0, m.index) + fragment + html.slice(m.index + m[0].length);
    writeFileSync(path, out, "utf8");
  }
  console.log(`build: fragment de boot (BG/LIGHT) ← themes.json → ${HTML_TARGETS.map((p) => p.split("/").pop()).join(", ")}`);
}

const builtThemes = build();
buildBootFragments(builtThemes);
