import type { FeatureImplementation } from "@headless-tree/core";

/**
 * Svelte prop remapping feature.
 *
 * Headless Tree generates React-compliant prop names (camelCase event
 * handlers like `onClick`, plus a React-style `ref`). Svelte 5 spreads
 * lowercase DOM event names (`onclick`) and has no `ref` — camelCase keys
 * in a `{...props}` spread would be set as plain attributes.
 *
 * This is the doc-recommended way to adapt the prop output to a non-React
 * framework (see https://headless-tree.lukasbach.com/recipe/plugins —
 * "Remapping Prop Names for different Frameworks other than React"): a
 * feature that overwrites the prop-generating methods and rewrites their
 * output.
 *
 * MUST be the LAST entry in the `features` array so its `prev` chain sees
 * every prop generated by the other features (including the ones added by
 * our own `mdvRowClickFeature`).
 *
 * The `ref` keys are dropped because element registration happens through
 * the Svelte action `registerItem` (`use:registerItem`) and `bind:this` on
 * the container.
 */
const EVENT_KEY_RE = /^on[A-Z]/;

function remapProps(props: Record<string, unknown>): Record<string, unknown> {
  const out: Record<string, unknown> = {};
  for (const [key, value] of Object.entries(props)) {
    if (key === "ref") continue;
    if (EVENT_KEY_RE.test(key) && typeof value === "function") {
      out[key.toLowerCase()] = value;
    } else {
      out[key] = value;
    }
  }
  return out;
}

export const sveltePropsFeature: FeatureImplementation = {
  key: "svelteProps",
  itemInstance: {
    getProps: ({ prev }) => remapProps(prev?.() ?? {}),
  },
  treeInstance: {
    // The treeLabel travels through the chain like the built-in
    // dragAndDropFeature does (prev?.(label)).
    getContainerProps: ({ prev }, label) => remapProps(prev?.(label) ?? {}),
  },
};
